### ISSUE TITLE
Make the prototype

### ISSUE THREAD

**Issue by An-miyoung** [pshdev1030/pig_the_dice#12]
##Task

- [x] make a html page
- [x] make a style-sheet
- [x] make js codes

**Comment by An-miyoung** [comment]
resolve #12
